// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKRny9ceceBHmevM6sOACvTTuoyjatZLk',
    appId: '1:336145846798:web:83b8b13ac65833ec7fe25f',
    messagingSenderId: '336145846798',
    projectId: 'whatsapp-aae5b',
    authDomain: 'whatsapp-aae5b.firebaseapp.com',
    storageBucket: 'whatsapp-aae5b.appspot.com',
    measurementId: 'G-0P1M3YF5PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6IRc5veCzU2ukvmr9AONDZN6krk7FTr8',
    appId: '1:336145846798:android:02ab64f0e3d9ec3f7fe25f',
    messagingSenderId: '336145846798',
    projectId: 'whatsapp-aae5b',
    storageBucket: 'whatsapp-aae5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNel6CvybWLbj8K4tePp9FcCxyX29ae6g',
    appId: '1:336145846798:ios:9e60f4026279cb9e7fe25f',
    messagingSenderId: '336145846798',
    projectId: 'whatsapp-aae5b',
    storageBucket: 'whatsapp-aae5b.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNel6CvybWLbj8K4tePp9FcCxyX29ae6g',
    appId: '1:336145846798:ios:ea19be12f017b3ed7fe25f',
    messagingSenderId: '336145846798',
    projectId: 'whatsapp-aae5b',
    storageBucket: 'whatsapp-aae5b.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger.RunnerTests',
  );
}
